/**
 * generated by Xtext 2.12.0
 */
package com.yakindu.solidity.ui.contentassist;

import com.yakindu.solidity.ui.contentassist.AbstractSolidityProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SolidityProposalProvider extends AbstractSolidityProposalProvider {
}
