/**
 * Copyright (c) 2017 committers of YAKINDU and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 * 	Andreas Muelder - Itemis AG - initial API and implementation
 * 	Karsten Thoms   - Itemis AG - initial API and implementation
 * 	Florian Antony  - Itemis AG - initial API and implementation
 * 	committers of YAKINDU 
 * 
 */
package com.yakindu.solidity.validation;

/**
 * 
 * @author Karsten Thoms - Initial contribution and API
 * @author Florian Antony
 */
public interface IssueCodes {
	// Compiler ERRORS
	String ERROR_CONSTANT_MODIFIER_WAS_REMOVED = "ERROR_CONSTANT_MODIFIER_WAS_REMOVED";
	String ERROR_DATA_LOCATION_MUST_BE_CALLDATA_FOR_EXTERNAL_PARAMETER = "ERROR_DATA_LOCATION_MUST_BE_CALLDATA_FOR_EXTERNAL_PARAMETER";
	String ERROR_DATA_LOCATION_MUST_BE_MEMORY_FOR_PARAMETER = "ERROR_DATA_LOCATION_MUST_BE_MEMORY_FOR_PARAMETER";
	String ERROR_DATA_LOCATION_MUST_BE_MEMORY_FOR_RETURN_PARAMETER = "ERROR_DATA_LOCATION_MUST_BE_MEMORY_FOR_RETURN_PARAMETER";
	String ERROR_DATA_LOCATION_MUST_BE_MEMORY_OR_STORAGE_FOR_RETURN_PARAMETER = "ERROR_DATA_LOCATION_MUST_BE_MEMORY_OR_STORAGE_FOR_RETURN_PARAMETER";
	String ERROR_DATA_LOCATION_MUST_BE_SPECIFIED_FOR_VARIABLE = "ERROR_DATA_LOCATION_MUST_BE_SPECIFIED_FOR_VARIABLE";
	String ERROR_DATA_LOCATION_MUST_BE_STORAGE_OR_MEMORY_FOR_PARAMETER = "ERROR_DATA_LOCATION_MUST_BE_STORAGE_OR_MEMORY_FOR_PARAMETER";
	String ERROR_FUNCTION_DECLARED_AS_PURE_BUT_MUST_BE_VIEW = "ERROR_FUNCTION_DECLARED_AS_PURE_BUT_MUST_BE_VIEW";
	String ERROR_FUNCTION_DECLARED_AS_VIEW_BUT_MUST_BE_PAYABLE_OR_NON_PAYABLE = "ERROR_FUNCTION_DECLARED_AS_VIEW_BUT_MUST_BE_PAYABLE_OR_NON_PAYABLE";
	String ERROR_FUNCTION_NAME_EQUALS_CONTRACT_NAME_DISALLOWED = "ERROR_FUNCTION_NAME_EQUALS_CONTRACT_NAME_DISALLOWED";
	String ERROR_INVALID_IMPLICID_CONVERSION_TO_ADDRESS_PAYABLE = "ERROR_INVALID_IMPLICID_CONVERSION_TO_ADDRESS_PAYABLE";
	String ERROR_MEMBER_TRANSFER_NOT_FOUND_OR_VISIBLE = "ERROR_MEMBER_TRANSFER_NOT_FOUND_OR_VISIBLE";
	String ERROR_NO_VISIBILITY_SPECIFIED = "ERROR_NO_VISIBILITY_SPECIFIED";
	String ERROR_STATE_MUTABILITY_ONLY_ALLOWED_FOR_ADDRESS = "ERROR_STATE_MUTABILITY_ONLY_ALLOWED_FOR_ADDRESS";
	String ERROR_THROW_KEYWORD_DISALLOWED = "ERROR_THROW_KEYWORD_DISALLOWED";
	String ERROR_VAR_KEYWORD_DISALLOWED = "ERROR_VAR_KEYWORD_DISALLOWED";
	String ERROR_YEARS_IS_DISALLOWED = "ERROR_YEARS_IS_DISALLOWED";
	String ERROR_DEPRECATED_SUICIDE = "ERROR_DEPRECATED_SUICIDE";
	String ERROR_DEPRECATED_SHA3 = "ERROR_DEPRECATED_SHA3";
	String ERROR_MSG_VALUE_ONLY_ALLOWED_IN_PAYABLE = "ERROR_MSG_VALUE_ONLY_ALLOWED_IN_PAYABLE";

	// Compiler WARNINGS
	String WARNING_DEPRECATED_CALLCODE = "WARNING_DEPRECATED_CALLCODE";
	String WARNING_DEPRECATED_FUNCTION_CONSTRUCTOR = "WARNING_DEPRECATED_FUNCTION_CONSTRUCTOR";
	String WARNING_DEPRECATED_NAMED_FUNCTION_PARAMETERS = "WARNING_DEPRECATED_NAMED_FUNCTION_PARAMETERS";
	String WARNING_DEPRECATED_NAMED_FUNCTION_RETURN_VALUES = "WARNING_DEPRECATED_NAMED_FUNCTION_RETURN_VALUES";
	String WARNING_DEPRECATED_SHA3 = "WARNING_DEPRECATED_SHA3";
	String WARNING_DEPRECATED_SUICIDE = "WARNING_DEPRECATED_SUICIDE";
	String WARNING_DEPRECATED_THROW = "WARNING_DEPRECATED_THROW";
	String WARNING_FILE_NO_PRAGMA_SOLIDITY = "WARNING_FILE_NO_PRAGMA_SOLIDITY";
	String WARNING_FUNCTION_STATE_MUTABILITY_PURE = "WARNING_FUNCTION_STATE_MUTABILITY_PURE";
	String WARNING_FUNCTION_STATE_MUTABILITY_VIEW = "WARNING_FUNCTION_STATE_MUTABILITY_VIEW";
	String WARNING_FUNCTION_UNUSED_PARAMETER = "WARNING_FUNCTION_UNUSED_PARAMETER";
	String WARNING_FUNCTION_VISIBILITY = "WARNING_FUNCTION_VISIBILITY";
	String WARNING_LOCAL_VARIABLE_UNUSED = "WARNING_LOCAL_VARIABLE_UNUSED";
	String WARNING_MSG_VALUE_IN_NON_PAYABLE = "WARNING_MSG_VALUE_IN_NON_PAYABLE";
	String WARNING_SHADOWED_DECLARATION = "WARNING_SHADOWED_DECLARATION";
	String WARNING_SOLIDITY_VERSION_NOT_THE_DEFAULT = "WARNING_SOLIDITY_VERSION_NOT_THE_DEFAULT";
	String WARNING_USSAGE_OF_SEND = "WARNING_USSAGE_OF_SEND";
	String WARNING_VARIABLE_STORAGE_POINTER = "WARNING_VARIABLE_STORAGE_POINTER";

}
