/*
 * generated by Xtext 2.12.0
 */
package com.yakindu.solidity.serializer;

import com.google.inject.Inject;
import com.yakindu.solidity.services.SolidityGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class SoliditySyntacticSequencer extends AbstractSyntacticSequencer {

	protected SolidityGrammarAccess grammarAccess;
	protected AbstractElementAlias match_FunctionDefinition_ReturnsKeyword_7_0_q;
	protected AbstractElementAlias match_FunctionDefinition___ConstantKeyword_6_4_or_ExternalKeyword_6_0_or_InternalKeyword_6_2_or_PrivateKeyword_6_3_or_PublicKeyword_6_1__a;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (SolidityGrammarAccess) access;
		match_FunctionDefinition_ReturnsKeyword_7_0_q = new TokenAlias(false, true, grammarAccess.getFunctionDefinitionAccess().getReturnsKeyword_7_0());
		match_FunctionDefinition___ConstantKeyword_6_4_or_ExternalKeyword_6_0_or_InternalKeyword_6_2_or_PrivateKeyword_6_3_or_PublicKeyword_6_1__a = new AlternativeAlias(true, true, new TokenAlias(false, false, grammarAccess.getFunctionDefinitionAccess().getConstantKeyword_6_4()), new TokenAlias(false, false, grammarAccess.getFunctionDefinitionAccess().getExternalKeyword_6_0()), new TokenAlias(false, false, grammarAccess.getFunctionDefinitionAccess().getInternalKeyword_6_2()), new TokenAlias(false, false, grammarAccess.getFunctionDefinitionAccess().getPrivateKeyword_6_3()), new TokenAlias(false, false, grammarAccess.getFunctionDefinitionAccess().getPublicKeyword_6_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getBitwiseAndOperatorRule())
			return getBitwiseAndOperatorToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getBitwiseOrOperatorRule())
			return getBitwiseOrOperatorToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getBitwiseXOrOperatorRule())
			return getBitwiseXOrOperatorToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getLogicalAndOperatorRule())
			return getLogicalAndOperatorToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getLogicalNotOperatorRule())
			return getLogicalNotOperatorToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getLogicalOrOperatorRule())
			return getLogicalOrOperatorToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * BitwiseAndOperator:
	 * 	'&';
	 */
	protected String getBitwiseAndOperatorToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "&";
	}
	
	/**
	 * BitwiseOrOperator:
	 * 	'|';
	 */
	protected String getBitwiseOrOperatorToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "|";
	}
	
	/**
	 * BitwiseXOrOperator:
	 * 	'^';
	 */
	protected String getBitwiseXOrOperatorToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "^";
	}
	
	/**
	 * LogicalAndOperator:
	 * 	'&&';
	 */
	protected String getLogicalAndOperatorToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "&&";
	}
	
	/**
	 * LogicalNotOperator:
	 * 	'!';
	 */
	protected String getLogicalNotOperatorToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "!";
	}
	
	/**
	 * LogicalOrOperator:
	 * 	'||';
	 */
	protected String getLogicalOrOperatorToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "||";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_FunctionDefinition_ReturnsKeyword_7_0_q.equals(syntax))
				emit_FunctionDefinition_ReturnsKeyword_7_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_FunctionDefinition___ConstantKeyword_6_4_or_ExternalKeyword_6_0_or_InternalKeyword_6_2_or_PrivateKeyword_6_3_or_PublicKeyword_6_1__a.equals(syntax))
				emit_FunctionDefinition___ConstantKeyword_6_4_or_ExternalKeyword_6_0_or_InternalKeyword_6_2_or_PrivateKeyword_6_3_or_PublicKeyword_6_1__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'returns'?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'function' '(' ')' ('constant' | 'public' | 'private' | 'external' | 'internal')* (ambiguity) ';' (rule start)
	 *     (rule start) 'function' '(' ')' ('constant' | 'public' | 'private' | 'external' | 'internal')* (ambiguity) block=Block
	 *     name=ID '(' ')' ('constant' | 'public' | 'private' | 'external' | 'internal')* (ambiguity) ';' (rule end)
	 *     name=ID '(' ')' ('constant' | 'public' | 'private' | 'external' | 'internal')* (ambiguity) block=Block
	 *     parameters+=Parameter ')' ('constant' | 'public' | 'private' | 'external' | 'internal')* (ambiguity) ';' (rule end)
	 *     parameters+=Parameter ')' ('constant' | 'public' | 'private' | 'external' | 'internal')* (ambiguity) block=Block
	 */
	protected void emit_FunctionDefinition_ReturnsKeyword_7_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('constant' | 'public' | 'private' | 'external' | 'internal')*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'function' '(' ')' (ambiguity) 'returns' returnTypes+=TypeSpecifier
	 *     (rule start) 'function' '(' ')' (ambiguity) 'returns'? ';' (rule start)
	 *     (rule start) 'function' '(' ')' (ambiguity) 'returns'? block=Block
	 *     name=ID '(' ')' (ambiguity) 'returns' returnTypes+=TypeSpecifier
	 *     name=ID '(' ')' (ambiguity) 'returns'? ';' (rule end)
	 *     name=ID '(' ')' (ambiguity) 'returns'? block=Block
	 *     parameters+=Parameter ')' (ambiguity) 'returns' returnTypes+=TypeSpecifier
	 *     parameters+=Parameter ')' (ambiguity) 'returns'? ';' (rule end)
	 *     parameters+=Parameter ')' (ambiguity) 'returns'? block=Block
	 */
	protected void emit_FunctionDefinition___ConstantKeyword_6_4_or_ExternalKeyword_6_0_or_InternalKeyword_6_2_or_PrivateKeyword_6_3_or_PublicKeyword_6_1__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
