<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>*.sol</string>
	</array>
	<key>name</key>
	<string>solidity</string>
	<key>patterns</key>
	<array>
		<!-- TODO Keywords -->
		<dict>
			<key>name</key>
			<string>keyword.control.sol</string>
			<key>match</key>
			<string>\b(pragma|solidity|experimental|import|is|as|contract|library|interface|using|for|constant|mapping|memory|storage|public|internal|private)\b</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.sol</string>
</dict>
</plist>
