/**
 * generated by Xtext 2.18.0
 */
package com.yakindu.solidity.solidity;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assembly Default Switch Case</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yakindu.solidity.solidity.AssemblyDefaultSwitchCase#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see com.yakindu.solidity.solidity.SolidityPackage#getAssemblyDefaultSwitchCase()
 * @model
 * @generated
 */
public interface AssemblyDefaultSwitchCase extends EObject {
	/**
	 * Returns the value of the '<em><b>Body</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Body</em>' containment reference.
	 * @see #setBody(InlineAssemblyBlock)
	 * @see com.yakindu.solidity.solidity.SolidityPackage#getAssemblyDefaultSwitchCase_Body()
	 * @model containment="true"
	 * @generated
	 */
	InlineAssemblyBlock getBody();

	/**
	 * Sets the value of the '{@link com.yakindu.solidity.solidity.AssemblyDefaultSwitchCase#getBody <em>Body</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Body</em>' containment reference.
	 * @see #getBody()
	 * @generated
	 */
	void setBody(InlineAssemblyBlock value);

} // AssemblyDefaultSwitchCase
