/**
 * generated by Xtext 2.18.0
 */
package com.yakindu.solidity.solidity;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Continue Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.yakindu.solidity.solidity.SolidityPackage#getContinueStatement()
 * @model
 * @generated
 */
public interface ContinueStatement extends Statement {
} // ContinueStatement
