/**
 * generated by Xtext 2.18.0
 */
package com.yakindu.solidity.solidity;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pragma Version Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yakindu.solidity.solidity.PragmaVersionConstraint#getVersionOperator <em>Version Operator</em>}</li>
 *   <li>{@link com.yakindu.solidity.solidity.PragmaVersionConstraint#getVersion <em>Version</em>}</li>
 * </ul>
 *
 * @see com.yakindu.solidity.solidity.SolidityPackage#getPragmaVersionConstraint()
 * @model
 * @generated
 */
public interface PragmaVersionConstraint extends EObject {
	/**
	 * Returns the value of the '<em><b>Version Operator</b></em>' attribute.
	 * The literals are from the enumeration {@link com.yakindu.solidity.solidity.VersionOperator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Version Operator</em>' attribute.
	 * @see com.yakindu.solidity.solidity.VersionOperator
	 * @see #setVersionOperator(VersionOperator)
	 * @see com.yakindu.solidity.solidity.SolidityPackage#getPragmaVersionConstraint_VersionOperator()
	 * @model
	 * @generated
	 */
	VersionOperator getVersionOperator();

	/**
	 * Sets the value of the '{@link com.yakindu.solidity.solidity.PragmaVersionConstraint#getVersionOperator <em>Version Operator</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Version Operator</em>' attribute.
	 * @see com.yakindu.solidity.solidity.VersionOperator
	 * @see #getVersionOperator()
	 * @generated
	 */
	void setVersionOperator(VersionOperator value);

	/**
	 * Returns the value of the '<em><b>Version</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Version</em>' attribute.
	 * @see #setVersion(String)
	 * @see com.yakindu.solidity.solidity.SolidityPackage#getPragmaVersionConstraint_Version()
	 * @model
	 * @generated
	 */
	String getVersion();

	/**
	 * Sets the value of the '{@link com.yakindu.solidity.solidity.PragmaVersionConstraint#getVersion <em>Version</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Version</em>' attribute.
	 * @see #getVersion()
	 * @generated
	 */
	void setVersion(String value);

} // PragmaVersionConstraint
