/**
 * generated by Xtext 2.18.0
 */
package com.yakindu.solidity.solidity;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pragma Version</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yakindu.solidity.solidity.PragmaVersion#getMinorConstraint <em>Minor Constraint</em>}</li>
 *   <li>{@link com.yakindu.solidity.solidity.PragmaVersion#getMajorConstraint <em>Major Constraint</em>}</li>
 * </ul>
 *
 * @see com.yakindu.solidity.solidity.SolidityPackage#getPragmaVersion()
 * @model
 * @generated
 */
public interface PragmaVersion extends EObject {
	/**
	 * Returns the value of the '<em><b>Minor Constraint</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Minor Constraint</em>' containment reference.
	 * @see #setMinorConstraint(PragmaVersionConstraint)
	 * @see com.yakindu.solidity.solidity.SolidityPackage#getPragmaVersion_MinorConstraint()
	 * @model containment="true"
	 * @generated
	 */
	PragmaVersionConstraint getMinorConstraint();

	/**
	 * Sets the value of the '{@link com.yakindu.solidity.solidity.PragmaVersion#getMinorConstraint <em>Minor Constraint</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Minor Constraint</em>' containment reference.
	 * @see #getMinorConstraint()
	 * @generated
	 */
	void setMinorConstraint(PragmaVersionConstraint value);

	/**
	 * Returns the value of the '<em><b>Major Constraint</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Major Constraint</em>' containment reference.
	 * @see #setMajorConstraint(PragmaVersionConstraint)
	 * @see com.yakindu.solidity.solidity.SolidityPackage#getPragmaVersion_MajorConstraint()
	 * @model containment="true"
	 * @generated
	 */
	PragmaVersionConstraint getMajorConstraint();

	/**
	 * Sets the value of the '{@link com.yakindu.solidity.solidity.PragmaVersion#getMajorConstraint <em>Major Constraint</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Major Constraint</em>' containment reference.
	 * @see #getMajorConstraint()
	 * @generated
	 */
	void setMajorConstraint(PragmaVersionConstraint value);

} // PragmaVersion
