/**
 * generated by Xtext 2.18.0
 */
package com.yakindu.solidity.solidity;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pragma Solidity Directive</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yakindu.solidity.solidity.PragmaSolidityDirective#getVersion <em>Version</em>}</li>
 * </ul>
 *
 * @see com.yakindu.solidity.solidity.SolidityPackage#getPragmaSolidityDirective()
 * @model
 * @generated
 */
public interface PragmaSolidityDirective extends PragmaDirective {
	/**
	 * Returns the value of the '<em><b>Version</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Version</em>' containment reference.
	 * @see #setVersion(PragmaVersion)
	 * @see com.yakindu.solidity.solidity.SolidityPackage#getPragmaSolidityDirective_Version()
	 * @model containment="true"
	 * @generated
	 */
	PragmaVersion getVersion();

	/**
	 * Sets the value of the '{@link com.yakindu.solidity.solidity.PragmaSolidityDirective#getVersion <em>Version</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Version</em>' containment reference.
	 * @see #getVersion()
	 * @generated
	 */
	void setVersion(PragmaVersion value);

} // PragmaSolidityDirective
