/**
 * generated by Xtext 2.18.0
 */
package com.yakindu.solidity.solidity;

import org.yakindu.base.base.DomainElement;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pragma Directive</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.yakindu.solidity.solidity.SolidityPackage#getPragmaDirective()
 * @model
 * @generated
 */
public interface PragmaDirective extends DomainElement {
} // PragmaDirective
