/**
 * generated by Xtext 2.18.0
 */
package com.yakindu.solidity.solidity;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Type Specifier</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.yakindu.solidity.solidity.SolidityPackage#getSimpleTypeSpecifier()
 * @model
 * @generated
 */
public interface SimpleTypeSpecifier extends TypeSpecifier {
} // SimpleTypeSpecifier
