/**
 * generated by Xtext 2.18.0
 */
package com.yakindu.solidity.solidity;

import org.eclipse.emf.common.util.EList;

import org.yakindu.base.expressions.expressions.FeatureCall;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feature Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yakindu.solidity.solidity.SolidityFeatureCall#getCalloptions <em>Calloptions</em>}</li>
 * </ul>
 *
 * @see com.yakindu.solidity.solidity.SolidityPackage#getSolidityFeatureCall()
 * @model
 * @generated
 */
public interface SolidityFeatureCall extends FeatureCall {
	/**
	 * Returns the value of the '<em><b>Calloptions</b></em>' containment reference list.
	 * The list contents are of type {@link com.yakindu.solidity.solidity.NamedArgument}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Calloptions</em>' containment reference list.
	 * @see com.yakindu.solidity.solidity.SolidityPackage#getSolidityFeatureCall_Calloptions()
	 * @model containment="true"
	 * @generated
	 */
	EList<NamedArgument> getCalloptions();

} // SolidityFeatureCall
