/**
 * generated by Xtext 2.18.0
 */
package com.yakindu.solidity.solidity;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.yakindu.solidity.solidity.SolidityPackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject {
} // Statement
