/**
 * generated by Xtext 2.18.0
 */
package com.yakindu.solidity.solidity;

import org.yakindu.base.types.ComplexType;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Struct Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.yakindu.solidity.solidity.SolidityPackage#getStructDefinition()
 * @model
 * @generated
 */
public interface StructDefinition extends ComplexType {
} // StructDefinition
