/**
 * generated by Xtext 2.18.0
 */
package com.yakindu.solidity.solidity;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Specifier</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.yakindu.solidity.solidity.SolidityPackage#getTypeSpecifier()
 * @model
 * @generated
 */
public interface TypeSpecifier extends org.yakindu.base.types.TypeSpecifier {
} // TypeSpecifier
