/**
 * generated by Xtext 2.18.0
 */
package com.yakindu.solidity.solidity;

import org.yakindu.base.types.Declaration;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Using For Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.yakindu.solidity.solidity.UsingForDeclaration#getContract <em>Contract</em>}</li>
 *   <li>{@link com.yakindu.solidity.solidity.UsingForDeclaration#getTypeSpecifier <em>Type Specifier</em>}</li>
 * </ul>
 *
 * @see com.yakindu.solidity.solidity.SolidityPackage#getUsingForDeclaration()
 * @model
 * @generated
 */
public interface UsingForDeclaration extends Declaration {
	/**
	 * Returns the value of the '<em><b>Contract</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Contract</em>' reference.
	 * @see #setContract(ContractDefinition)
	 * @see com.yakindu.solidity.solidity.SolidityPackage#getUsingForDeclaration_Contract()
	 * @model
	 * @generated
	 */
	ContractDefinition getContract();

	/**
	 * Sets the value of the '{@link com.yakindu.solidity.solidity.UsingForDeclaration#getContract <em>Contract</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Contract</em>' reference.
	 * @see #getContract()
	 * @generated
	 */
	void setContract(ContractDefinition value);

	/**
	 * Returns the value of the '<em><b>Type Specifier</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Type Specifier</em>' containment reference.
	 * @see #setTypeSpecifier(TypeSpecifier)
	 * @see com.yakindu.solidity.solidity.SolidityPackage#getUsingForDeclaration_TypeSpecifier()
	 * @model containment="true"
	 * @generated
	 */
	TypeSpecifier getTypeSpecifier();

	/**
	 * Sets the value of the '{@link com.yakindu.solidity.solidity.UsingForDeclaration#getTypeSpecifier <em>Type Specifier</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Type Specifier</em>' containment reference.
	 * @see #getTypeSpecifier()
	 * @generated
	 */
	void setTypeSpecifier(TypeSpecifier value);

} // UsingForDeclaration
