/**
 * generated by Xtext 2.18.0
 */
package com.yakindu.solidity.solidity.impl;

import com.yakindu.solidity.solidity.AssemblyForExpression;
import com.yakindu.solidity.solidity.FunctionalAssemblyExpression;
import com.yakindu.solidity.solidity.InlineAssemblyBlock;
import com.yakindu.solidity.solidity.SolidityPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Assembly For Expression</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.yakindu.solidity.solidity.impl.AssemblyForExpressionImpl#getPrestatementblock <em>Prestatementblock</em>}</li>
 *   <li>{@link com.yakindu.solidity.solidity.impl.AssemblyForExpressionImpl#getCondition <em>Condition</em>}</li>
 *   <li>{@link com.yakindu.solidity.solidity.impl.AssemblyForExpressionImpl#getLoopstatementblock <em>Loopstatementblock</em>}</li>
 *   <li>{@link com.yakindu.solidity.solidity.impl.AssemblyForExpressionImpl#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AssemblyForExpressionImpl extends AssemblyExpressionImpl implements AssemblyForExpression {
	/**
	 * The cached value of the '{@link #getPrestatementblock() <em>Prestatementblock</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getPrestatementblock()
	 * @generated
	 * @ordered
	 */
	protected InlineAssemblyBlock prestatementblock;

	/**
	 * The cached value of the '{@link #getCondition() <em>Condition</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getCondition()
	 * @generated
	 * @ordered
	 */
	protected FunctionalAssemblyExpression condition;

	/**
	 * The cached value of the '{@link #getLoopstatementblock() <em>Loopstatementblock</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getLoopstatementblock()
	 * @generated
	 * @ordered
	 */
	protected InlineAssemblyBlock loopstatementblock;

	/**
	 * The cached value of the '{@link #getBody() <em>Body</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getBody()
	 * @generated
	 * @ordered
	 */
	protected InlineAssemblyBlock body;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AssemblyForExpressionImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return SolidityPackage.Literals.ASSEMBLY_FOR_EXPRESSION;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public InlineAssemblyBlock getPrestatementblock() {
		return prestatementblock;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetPrestatementblock(InlineAssemblyBlock newPrestatementblock, NotificationChain msgs) {
		InlineAssemblyBlock oldPrestatementblock = prestatementblock;
		prestatementblock = newPrestatementblock;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SolidityPackage.ASSEMBLY_FOR_EXPRESSION__PRESTATEMENTBLOCK, oldPrestatementblock, newPrestatementblock);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setPrestatementblock(InlineAssemblyBlock newPrestatementblock) {
		if (newPrestatementblock != prestatementblock) {
			NotificationChain msgs = null;
			if (prestatementblock != null)
				msgs = ((InternalEObject)prestatementblock).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SolidityPackage.ASSEMBLY_FOR_EXPRESSION__PRESTATEMENTBLOCK, null, msgs);
			if (newPrestatementblock != null)
				msgs = ((InternalEObject)newPrestatementblock).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SolidityPackage.ASSEMBLY_FOR_EXPRESSION__PRESTATEMENTBLOCK, null, msgs);
			msgs = basicSetPrestatementblock(newPrestatementblock, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, SolidityPackage.ASSEMBLY_FOR_EXPRESSION__PRESTATEMENTBLOCK, newPrestatementblock, newPrestatementblock));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public FunctionalAssemblyExpression getCondition() {
		return condition;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetCondition(FunctionalAssemblyExpression newCondition, NotificationChain msgs) {
		FunctionalAssemblyExpression oldCondition = condition;
		condition = newCondition;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SolidityPackage.ASSEMBLY_FOR_EXPRESSION__CONDITION, oldCondition, newCondition);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setCondition(FunctionalAssemblyExpression newCondition) {
		if (newCondition != condition) {
			NotificationChain msgs = null;
			if (condition != null)
				msgs = ((InternalEObject)condition).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SolidityPackage.ASSEMBLY_FOR_EXPRESSION__CONDITION, null, msgs);
			if (newCondition != null)
				msgs = ((InternalEObject)newCondition).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SolidityPackage.ASSEMBLY_FOR_EXPRESSION__CONDITION, null, msgs);
			msgs = basicSetCondition(newCondition, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, SolidityPackage.ASSEMBLY_FOR_EXPRESSION__CONDITION, newCondition, newCondition));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public InlineAssemblyBlock getLoopstatementblock() {
		return loopstatementblock;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetLoopstatementblock(InlineAssemblyBlock newLoopstatementblock, NotificationChain msgs) {
		InlineAssemblyBlock oldLoopstatementblock = loopstatementblock;
		loopstatementblock = newLoopstatementblock;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SolidityPackage.ASSEMBLY_FOR_EXPRESSION__LOOPSTATEMENTBLOCK, oldLoopstatementblock, newLoopstatementblock);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setLoopstatementblock(InlineAssemblyBlock newLoopstatementblock) {
		if (newLoopstatementblock != loopstatementblock) {
			NotificationChain msgs = null;
			if (loopstatementblock != null)
				msgs = ((InternalEObject)loopstatementblock).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SolidityPackage.ASSEMBLY_FOR_EXPRESSION__LOOPSTATEMENTBLOCK, null, msgs);
			if (newLoopstatementblock != null)
				msgs = ((InternalEObject)newLoopstatementblock).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SolidityPackage.ASSEMBLY_FOR_EXPRESSION__LOOPSTATEMENTBLOCK, null, msgs);
			msgs = basicSetLoopstatementblock(newLoopstatementblock, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, SolidityPackage.ASSEMBLY_FOR_EXPRESSION__LOOPSTATEMENTBLOCK, newLoopstatementblock, newLoopstatementblock));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public InlineAssemblyBlock getBody() {
		return body;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetBody(InlineAssemblyBlock newBody, NotificationChain msgs) {
		InlineAssemblyBlock oldBody = body;
		body = newBody;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SolidityPackage.ASSEMBLY_FOR_EXPRESSION__BODY, oldBody, newBody);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setBody(InlineAssemblyBlock newBody) {
		if (newBody != body) {
			NotificationChain msgs = null;
			if (body != null)
				msgs = ((InternalEObject)body).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SolidityPackage.ASSEMBLY_FOR_EXPRESSION__BODY, null, msgs);
			if (newBody != null)
				msgs = ((InternalEObject)newBody).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SolidityPackage.ASSEMBLY_FOR_EXPRESSION__BODY, null, msgs);
			msgs = basicSetBody(newBody, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, SolidityPackage.ASSEMBLY_FOR_EXPRESSION__BODY, newBody, newBody));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs) {
		switch (featureID) {
			case SolidityPackage.ASSEMBLY_FOR_EXPRESSION__PRESTATEMENTBLOCK:
				return basicSetPrestatementblock(null, msgs);
			case SolidityPackage.ASSEMBLY_FOR_EXPRESSION__CONDITION:
				return basicSetCondition(null, msgs);
			case SolidityPackage.ASSEMBLY_FOR_EXPRESSION__LOOPSTATEMENTBLOCK:
				return basicSetLoopstatementblock(null, msgs);
			case SolidityPackage.ASSEMBLY_FOR_EXPRESSION__BODY:
				return basicSetBody(null, msgs);
		}
		return super.eInverseRemove(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType) {
		switch (featureID) {
			case SolidityPackage.ASSEMBLY_FOR_EXPRESSION__PRESTATEMENTBLOCK:
				return getPrestatementblock();
			case SolidityPackage.ASSEMBLY_FOR_EXPRESSION__CONDITION:
				return getCondition();
			case SolidityPackage.ASSEMBLY_FOR_EXPRESSION__LOOPSTATEMENTBLOCK:
				return getLoopstatementblock();
			case SolidityPackage.ASSEMBLY_FOR_EXPRESSION__BODY:
				return getBody();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eSet(int featureID, Object newValue) {
		switch (featureID) {
			case SolidityPackage.ASSEMBLY_FOR_EXPRESSION__PRESTATEMENTBLOCK:
				setPrestatementblock((InlineAssemblyBlock)newValue);
				return;
			case SolidityPackage.ASSEMBLY_FOR_EXPRESSION__CONDITION:
				setCondition((FunctionalAssemblyExpression)newValue);
				return;
			case SolidityPackage.ASSEMBLY_FOR_EXPRESSION__LOOPSTATEMENTBLOCK:
				setLoopstatementblock((InlineAssemblyBlock)newValue);
				return;
			case SolidityPackage.ASSEMBLY_FOR_EXPRESSION__BODY:
				setBody((InlineAssemblyBlock)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID) {
		switch (featureID) {
			case SolidityPackage.ASSEMBLY_FOR_EXPRESSION__PRESTATEMENTBLOCK:
				setPrestatementblock((InlineAssemblyBlock)null);
				return;
			case SolidityPackage.ASSEMBLY_FOR_EXPRESSION__CONDITION:
				setCondition((FunctionalAssemblyExpression)null);
				return;
			case SolidityPackage.ASSEMBLY_FOR_EXPRESSION__LOOPSTATEMENTBLOCK:
				setLoopstatementblock((InlineAssemblyBlock)null);
				return;
			case SolidityPackage.ASSEMBLY_FOR_EXPRESSION__BODY:
				setBody((InlineAssemblyBlock)null);
				return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID) {
		switch (featureID) {
			case SolidityPackage.ASSEMBLY_FOR_EXPRESSION__PRESTATEMENTBLOCK:
				return prestatementblock != null;
			case SolidityPackage.ASSEMBLY_FOR_EXPRESSION__CONDITION:
				return condition != null;
			case SolidityPackage.ASSEMBLY_FOR_EXPRESSION__LOOPSTATEMENTBLOCK:
				return loopstatementblock != null;
			case SolidityPackage.ASSEMBLY_FOR_EXPRESSION__BODY:
				return body != null;
		}
		return super.eIsSet(featureID);
	}

} //AssemblyForExpressionImpl
