/**
 * generated by Xtext 2.18.0
 */
package com.yakindu.solidity.solidity.impl;

import com.yakindu.solidity.solidity.AssemblyFunctionDefinition;
import com.yakindu.solidity.solidity.AssemblyParameter;
import com.yakindu.solidity.solidity.InlineAssemblyBlock;
import com.yakindu.solidity.solidity.SolidityPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Assembly Function Definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.yakindu.solidity.solidity.impl.AssemblyFunctionDefinitionImpl#getName <em>Name</em>}</li>
 *   <li>{@link com.yakindu.solidity.solidity.impl.AssemblyFunctionDefinitionImpl#getParameters <em>Parameters</em>}</li>
 *   <li>{@link com.yakindu.solidity.solidity.impl.AssemblyFunctionDefinitionImpl#getReturnParameters <em>Return Parameters</em>}</li>
 *   <li>{@link com.yakindu.solidity.solidity.impl.AssemblyFunctionDefinitionImpl#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AssemblyFunctionDefinitionImpl extends MinimalEObjectImpl.Container implements AssemblyFunctionDefinition {
	/**
	 * The default value of the '{@link #getName() <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getName()
	 * @generated
	 * @ordered
	 */
	protected static final String NAME_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getName()
	 * @generated
	 * @ordered
	 */
	protected String name = NAME_EDEFAULT;

	/**
	 * The cached value of the '{@link #getParameters() <em>Parameters</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getParameters()
	 * @generated
	 * @ordered
	 */
	protected EList<AssemblyParameter> parameters;

	/**
	 * The cached value of the '{@link #getReturnParameters() <em>Return Parameters</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getReturnParameters()
	 * @generated
	 * @ordered
	 */
	protected EList<AssemblyParameter> returnParameters;

	/**
	 * The cached value of the '{@link #getBody() <em>Body</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getBody()
	 * @generated
	 * @ordered
	 */
	protected InlineAssemblyBlock body;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AssemblyFunctionDefinitionImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return SolidityPackage.Literals.ASSEMBLY_FUNCTION_DEFINITION;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getName() {
		return name;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setName(String newName) {
		String oldName = name;
		name = newName;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__NAME, oldName, name));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EList<AssemblyParameter> getParameters() {
		if (parameters == null) {
			parameters = new EObjectContainmentEList<AssemblyParameter>(AssemblyParameter.class, this, SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__PARAMETERS);
		}
		return parameters;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EList<AssemblyParameter> getReturnParameters() {
		if (returnParameters == null) {
			returnParameters = new EObjectContainmentEList<AssemblyParameter>(AssemblyParameter.class, this, SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__RETURN_PARAMETERS);
		}
		return returnParameters;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public InlineAssemblyBlock getBody() {
		return body;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetBody(InlineAssemblyBlock newBody, NotificationChain msgs) {
		InlineAssemblyBlock oldBody = body;
		body = newBody;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__BODY, oldBody, newBody);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setBody(InlineAssemblyBlock newBody) {
		if (newBody != body) {
			NotificationChain msgs = null;
			if (body != null)
				msgs = ((InternalEObject)body).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__BODY, null, msgs);
			if (newBody != null)
				msgs = ((InternalEObject)newBody).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__BODY, null, msgs);
			msgs = basicSetBody(newBody, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__BODY, newBody, newBody));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs) {
		switch (featureID) {
			case SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__PARAMETERS:
				return ((InternalEList<?>)getParameters()).basicRemove(otherEnd, msgs);
			case SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__RETURN_PARAMETERS:
				return ((InternalEList<?>)getReturnParameters()).basicRemove(otherEnd, msgs);
			case SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__BODY:
				return basicSetBody(null, msgs);
		}
		return super.eInverseRemove(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType) {
		switch (featureID) {
			case SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__NAME:
				return getName();
			case SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__PARAMETERS:
				return getParameters();
			case SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__RETURN_PARAMETERS:
				return getReturnParameters();
			case SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__BODY:
				return getBody();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@SuppressWarnings("unchecked")
	@Override
	public void eSet(int featureID, Object newValue) {
		switch (featureID) {
			case SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__NAME:
				setName((String)newValue);
				return;
			case SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__PARAMETERS:
				getParameters().clear();
				getParameters().addAll((Collection<? extends AssemblyParameter>)newValue);
				return;
			case SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__RETURN_PARAMETERS:
				getReturnParameters().clear();
				getReturnParameters().addAll((Collection<? extends AssemblyParameter>)newValue);
				return;
			case SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__BODY:
				setBody((InlineAssemblyBlock)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID) {
		switch (featureID) {
			case SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__NAME:
				setName(NAME_EDEFAULT);
				return;
			case SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__PARAMETERS:
				getParameters().clear();
				return;
			case SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__RETURN_PARAMETERS:
				getReturnParameters().clear();
				return;
			case SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__BODY:
				setBody((InlineAssemblyBlock)null);
				return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID) {
		switch (featureID) {
			case SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__NAME:
				return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
			case SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__PARAMETERS:
				return parameters != null && !parameters.isEmpty();
			case SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__RETURN_PARAMETERS:
				return returnParameters != null && !returnParameters.isEmpty();
			case SolidityPackage.ASSEMBLY_FUNCTION_DEFINITION__BODY:
				return body != null;
		}
		return super.eIsSet(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String toString() {
		if (eIsProxy()) return super.toString();

		StringBuilder result = new StringBuilder(super.toString());
		result.append(" (name: ");
		result.append(name);
		result.append(')');
		return result.toString();
	}

} //AssemblyFunctionDefinitionImpl
