/**
 * generated by Xtext 2.18.0
 */
package com.yakindu.solidity.solidity.impl;

import com.yakindu.solidity.solidity.AssemblyDefaultSwitchCase;
import com.yakindu.solidity.solidity.AssemblySwitchCase;
import com.yakindu.solidity.solidity.AssemblySwitchExpression;
import com.yakindu.solidity.solidity.FunctionalAssemblyExpression;
import com.yakindu.solidity.solidity.SolidityPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Assembly Switch Expression</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.yakindu.solidity.solidity.impl.AssemblySwitchExpressionImpl#getCondition <em>Condition</em>}</li>
 *   <li>{@link com.yakindu.solidity.solidity.impl.AssemblySwitchExpressionImpl#getCases <em>Cases</em>}</li>
 *   <li>{@link com.yakindu.solidity.solidity.impl.AssemblySwitchExpressionImpl#getDefaultCase <em>Default Case</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AssemblySwitchExpressionImpl extends AssemblyExpressionImpl implements AssemblySwitchExpression {
	/**
	 * The cached value of the '{@link #getCondition() <em>Condition</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getCondition()
	 * @generated
	 * @ordered
	 */
	protected FunctionalAssemblyExpression condition;

	/**
	 * The cached value of the '{@link #getCases() <em>Cases</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getCases()
	 * @generated
	 * @ordered
	 */
	protected EList<AssemblySwitchCase> cases;

	/**
	 * The cached value of the '{@link #getDefaultCase() <em>Default Case</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getDefaultCase()
	 * @generated
	 * @ordered
	 */
	protected AssemblyDefaultSwitchCase defaultCase;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AssemblySwitchExpressionImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return SolidityPackage.Literals.ASSEMBLY_SWITCH_EXPRESSION;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public FunctionalAssemblyExpression getCondition() {
		return condition;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetCondition(FunctionalAssemblyExpression newCondition, NotificationChain msgs) {
		FunctionalAssemblyExpression oldCondition = condition;
		condition = newCondition;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SolidityPackage.ASSEMBLY_SWITCH_EXPRESSION__CONDITION, oldCondition, newCondition);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setCondition(FunctionalAssemblyExpression newCondition) {
		if (newCondition != condition) {
			NotificationChain msgs = null;
			if (condition != null)
				msgs = ((InternalEObject)condition).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SolidityPackage.ASSEMBLY_SWITCH_EXPRESSION__CONDITION, null, msgs);
			if (newCondition != null)
				msgs = ((InternalEObject)newCondition).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SolidityPackage.ASSEMBLY_SWITCH_EXPRESSION__CONDITION, null, msgs);
			msgs = basicSetCondition(newCondition, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, SolidityPackage.ASSEMBLY_SWITCH_EXPRESSION__CONDITION, newCondition, newCondition));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EList<AssemblySwitchCase> getCases() {
		if (cases == null) {
			cases = new EObjectContainmentEList<AssemblySwitchCase>(AssemblySwitchCase.class, this, SolidityPackage.ASSEMBLY_SWITCH_EXPRESSION__CASES);
		}
		return cases;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public AssemblyDefaultSwitchCase getDefaultCase() {
		return defaultCase;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetDefaultCase(AssemblyDefaultSwitchCase newDefaultCase, NotificationChain msgs) {
		AssemblyDefaultSwitchCase oldDefaultCase = defaultCase;
		defaultCase = newDefaultCase;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SolidityPackage.ASSEMBLY_SWITCH_EXPRESSION__DEFAULT_CASE, oldDefaultCase, newDefaultCase);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setDefaultCase(AssemblyDefaultSwitchCase newDefaultCase) {
		if (newDefaultCase != defaultCase) {
			NotificationChain msgs = null;
			if (defaultCase != null)
				msgs = ((InternalEObject)defaultCase).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SolidityPackage.ASSEMBLY_SWITCH_EXPRESSION__DEFAULT_CASE, null, msgs);
			if (newDefaultCase != null)
				msgs = ((InternalEObject)newDefaultCase).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SolidityPackage.ASSEMBLY_SWITCH_EXPRESSION__DEFAULT_CASE, null, msgs);
			msgs = basicSetDefaultCase(newDefaultCase, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, SolidityPackage.ASSEMBLY_SWITCH_EXPRESSION__DEFAULT_CASE, newDefaultCase, newDefaultCase));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs) {
		switch (featureID) {
			case SolidityPackage.ASSEMBLY_SWITCH_EXPRESSION__CONDITION:
				return basicSetCondition(null, msgs);
			case SolidityPackage.ASSEMBLY_SWITCH_EXPRESSION__CASES:
				return ((InternalEList<?>)getCases()).basicRemove(otherEnd, msgs);
			case SolidityPackage.ASSEMBLY_SWITCH_EXPRESSION__DEFAULT_CASE:
				return basicSetDefaultCase(null, msgs);
		}
		return super.eInverseRemove(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType) {
		switch (featureID) {
			case SolidityPackage.ASSEMBLY_SWITCH_EXPRESSION__CONDITION:
				return getCondition();
			case SolidityPackage.ASSEMBLY_SWITCH_EXPRESSION__CASES:
				return getCases();
			case SolidityPackage.ASSEMBLY_SWITCH_EXPRESSION__DEFAULT_CASE:
				return getDefaultCase();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@SuppressWarnings("unchecked")
	@Override
	public void eSet(int featureID, Object newValue) {
		switch (featureID) {
			case SolidityPackage.ASSEMBLY_SWITCH_EXPRESSION__CONDITION:
				setCondition((FunctionalAssemblyExpression)newValue);
				return;
			case SolidityPackage.ASSEMBLY_SWITCH_EXPRESSION__CASES:
				getCases().clear();
				getCases().addAll((Collection<? extends AssemblySwitchCase>)newValue);
				return;
			case SolidityPackage.ASSEMBLY_SWITCH_EXPRESSION__DEFAULT_CASE:
				setDefaultCase((AssemblyDefaultSwitchCase)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID) {
		switch (featureID) {
			case SolidityPackage.ASSEMBLY_SWITCH_EXPRESSION__CONDITION:
				setCondition((FunctionalAssemblyExpression)null);
				return;
			case SolidityPackage.ASSEMBLY_SWITCH_EXPRESSION__CASES:
				getCases().clear();
				return;
			case SolidityPackage.ASSEMBLY_SWITCH_EXPRESSION__DEFAULT_CASE:
				setDefaultCase((AssemblyDefaultSwitchCase)null);
				return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID) {
		switch (featureID) {
			case SolidityPackage.ASSEMBLY_SWITCH_EXPRESSION__CONDITION:
				return condition != null;
			case SolidityPackage.ASSEMBLY_SWITCH_EXPRESSION__CASES:
				return cases != null && !cases.isEmpty();
			case SolidityPackage.ASSEMBLY_SWITCH_EXPRESSION__DEFAULT_CASE:
				return defaultCase != null;
		}
		return super.eIsSet(featureID);
	}

} //AssemblySwitchExpressionImpl
