/**
 * generated by Xtext 2.18.0
 */
package com.yakindu.solidity.solidity.impl;

import com.yakindu.solidity.solidity.EventDefinition;
import com.yakindu.solidity.solidity.SolidityPackage;

import org.eclipse.emf.ecore.EClass;

import org.yakindu.base.types.impl.OperationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Event Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EventDefinitionImpl extends OperationImpl implements EventDefinition {
	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EventDefinitionImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return SolidityPackage.Literals.EVENT_DEFINITION;
	}

} //EventDefinitionImpl
