/**
 * generated by Xtext 2.12.0
 */
package com.yakindu.solidity.ide;

import com.yakindu.solidity.ide.AbstractSolidityIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SolidityIdeModule extends AbstractSolidityIdeModule {
}
