/**
 * generated by Xtext 2.12.0
 */
package com.yakindu.solidity.ui.quickfix;

import org.yakindu.base.expressions.ui.quickfix.ExpressionsQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class SolidityQuickfixProvider extends ExpressionsQuickfixProvider {
}
