/*
 * generated by Xtext 2.12.0
 */
package com.yakindu.solidity.validation;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;
import org.yakindu.base.expressions.validation.ExpressionsJavaValidator;

public abstract class AbstractSolidityValidator extends ExpressionsJavaValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>(super.getEPackages());
		result.add(com.yakindu.solidity.solidity.SolidityPackage.eINSTANCE);
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.yakindu.org/base/types/2.0.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.yakindu.org/base/expressions/Expressions"));
		return result;
	}
	
}
